### ISSUE TITLE
Backbone pre training 

### ISSUE THREAD

**Issue by ga1i13o** [chenwei746/EEVG#1]
Hello, and congrats on your nice work.
I have a couple of questions to help reproduce your paper
1. In the appendix, you mention that the ViT backbone that you used is pre trained on MS coco.is this the case as well for the other backbones that you used, like Swin-B?
2. When will you release the full code and model checkpoints?

Thanks in advance!

**Comment by chenwei746** [comment]
Hi, thank you for your interest!
  1. The ViT backbone is pre-trained on MSCOCO because we leverage the weights from ViTDet, which is pre-trained on MSCOCO. This ensures a fair comparison with VG-LAW which use the weights of ViTDet. Swin-B utilizes official weights that are not pre-trained on MSCOCO. 
  2. We have released model [checkpoints](https://hkustconnect-my.sharepoint.com/:f:/g/personal/wchendb_connect_ust_hk/EvQKjSt_RipOp0Xsiyso75YBUgWpIw3DQGqMaXldIb_aaQ?e=0w3oEb) and the [mask data](https://hkustconnect-my.sharepoint.com/:u:/g/personal/wchendb_connect_ust_hk/EbiPljj4dx5Ns-tAf3zR8_UBxiuM7kRh2VHKPoI6q58TcQ?e=WleUng).
